// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jHBpvlNbHUKTELSwQO9svxfhgVfPJyE',
    appId: '1:67935365883:web:0922a336751b72fdbd5e5e',
    messagingSenderId: '67935365883',
    projectId: 'habtrackoo',
    authDomain: 'habtrackoo.firebaseapp.com',
    storageBucket: 'habtrackoo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthbcZXIosOhYH2-BjdKOzvCaM3uIV4XI',
    appId: '1:67935365883:android:210996882e35d192bd5e5e',
    messagingSenderId: '67935365883',
    projectId: 'habtrackoo',
    storageBucket: 'habtrackoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPy4aN1TXfYNXb9JHNwVln4ytuRZwmVIA',
    appId: '1:67935365883:ios:ded52f81a906ecebbd5e5e',
    messagingSenderId: '67935365883',
    projectId: 'habtrackoo',
    storageBucket: 'habtrackoo.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPy4aN1TXfYNXb9JHNwVln4ytuRZwmVIA',
    appId: '1:67935365883:ios:ded52f81a906ecebbd5e5e',
    messagingSenderId: '67935365883',
    projectId: 'habtrackoo',
    storageBucket: 'habtrackoo.firebasestorage.app',
    iosBundleId: 'com.example.habitTracker',
  );
}
